### ISSUE TITLE
Snappy codec does not work

### ISSUE THREAD

**Issue by mikaelstaldal** [flavray/avro-rs#56]
When writing Avro data with the Snappy codec, it cannot be read by the Java implementation from Apache. And vice versa.

To reproduce, run this Rust program and redirect stdout to a file (`snappy.avro`):
```
[dependencies.avro-rs]
version = "0.6.1"
features = ["snappy"]
```

```
extern crate avro_rs;

use avro_rs::Codec;
use avro_rs::Schema;
use avro_rs::types::Record;
use avro_rs::Writer;
use std::io::{self, Write};

fn main() {
    let raw_schema = r#"
        {
            "type": "record",
            "name": "test",
            "fields": [
                {"name": "a", "type": "long", "default": 42},
                {"name": "b", "type": "string"}
            ]
        }
    "#;

    let schema = Schema::parse_str(raw_schema).unwrap();

    let mut writer = Writer::with_codec(&schema, io::stdout(), Codec::Snappy);
    let mut record = Record::new(writer.schema()).unwrap();
    record.put("a", 27i64);
    record.put("b", "foo");
    writer.append(record).unwrap();
    writer.flush().unwrap();
}

```

Then run
```
java -jar avro-tools-1.8.2.jar tojson snappy.avro
```

I get this error:
```
Exception in thread "main" org.apache.avro.AvroRuntimeException: java.io.IOException: FAILED_TO_UNCOMPRESS(5)
        at org.apache.avro.file.DataFileStream.hasNext(DataFileStream.java:210)
        at org.apache.avro.tool.DataFileReadTool.run(DataFileReadTool.java:76)
        at org.apache.avro.tool.Main.run(Main.java:87)
        at org.apache.avro.tool.Main.main(Main.java:76)
Caused by: java.io.IOException: FAILED_TO_UNCOMPRESS(5)
        at org.xerial.snappy.SnappyNative.throw_error(SnappyNative.java:84)
        at org.xerial.snappy.SnappyNative.rawUncompress(Native Method)
        at org.xerial.snappy.Snappy.rawUncompress(Snappy.java:444)
        at org.xerial.snappy.Snappy.uncompress(Snappy.java:480)
        at org.apache.avro.file.SnappyCodec.decompress(SnappyCodec.java:60)
        at org.apache.avro.file.DataFileStream$DataBlock.decompressUsing(DataFileStream.java:355)
        at org.apache.avro.file.DataFileStream.hasNext(DataFileStream.java:199)
        ... 3 more

```

(If I use Null or Deflate codec, it works as expected.)

**Comment by mikaelstaldal** [comment]
I think the problem is that arvo-rs uses the Snappy frame format (Reader and Writer from the snap library). It should use the raw format (Encoder and Decoder from the snap library). And also handle the CRC32 checksum (I don't think the snap library does that).

**Comment by mikaelstaldal** [comment]
Here is an example of a working Avro snappy decoder in Rust, using the same snap library:
https://github.com/dflemstr/rq/blob/master/serde-avro/src/de/read.rs#L129_L152
(Encoder is left as an exercise for the reader.)
